apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: "podmonitors.monitoring.coreos.com"
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: "monitoring.coreos.com"
  names:
    kind: PodMonitor
    plural: podmonitors
  scope: Namespaced
  version: v1
