apiVersion: {{ template "daemonset_api_version" . }}
kind: DaemonSet
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
    spec:
      priorityClassName: cubepaas-priority
      containers:
      - name: exporter-process
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - -procfs
        - /host/proc
        - -config.path
        - /config/process-config.yml
        {{- if not .Values.enabledThreads }}
        - -threads
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.ports.metrics.port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: proc
          mountPath: /host/proc/
      {{- if .Values.enabledRBAC }}
      serviceAccountName: {{ default (include "app.fullname" .) .Values.serviceAccountName }}
      {{- end }}
      nodeSelector:
        beta.kubernetes.io/os: linux
        {{- range .Values.nodeSelectors }}
        {{- $pair := regexSplit "=" . 2 }}
        {{- if eq 2 (len $pair) }}
        {{ (index $pair 0) }}: {{ (index $pair 1) }}
        {{- else }}
        {{ (index $pair 0) }}: ""
        {{- end }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "app.fullname" . }}
          items:
          - key: "process-config.yml"
            path: "process-config.yml"
      - name: proc
        hostPath:
          path: /proc
