apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql-secret
type: Opaque
data:
{{ if .Values.mysqlRootPassword }}
mysql-root-password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
{{ else }}
mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
{{ end }}
{{ if .Values.mysqlPassword }}
mysql-password:  {{ .Values.mysqlPassword | b64enc | quote }}
{{ else }}
mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
{{ end }}
mysql-user: {{ .Values.mysqlUser }}