{
 "title": "Nodes",
 "description": "Nearly all default values exported by Prometheus node exporter graphed.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host:",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"}) / (node_memory_SwapTotal_bytes{instance=\"$instance\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\"}) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$instance\"}) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - (node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Basic Net / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Memory Net Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=\"$instance\"}[5m])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_Buffers_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"} - node_memory_Slab_bytes{instance=\"$instance\"} - node_memory_PageTables_bytes{instance=\"$instance\"} - node_memory_SwapCached_bytes{instance=\"$instance\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=\"$instance\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=\"$instance\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=\"$instance\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=\"$instance\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
       "legendFormat": "Unused - Free memory unasigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$instance\"}",
       "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "I/O Usage Times",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$instance\",device=~\"[a-z]*[a-z]\"} [5m])",
       "legendFormat": "{{device}} - Milliseconds spent doing I/Os"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Detail Meminfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{instance=\"$instance\"}",
       "legendFormat": "Inactive - Memory which has been less recently used. It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "node_memory_Active_bytes{instance=\"$instance\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      }
     ]
    },
    {
     "title": "Memory Commited",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{instance=\"$instance\"}",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{instance=\"$instance\"}",
       "legendFormat": "CommitLimit - Amount of memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{instance=\"$instance\"}",
       "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{instance=\"$instance\"}",
       "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
      },
      {
       "expr": "node_memory_Active_file_bytes{instance=\"$instance\"}",
       "legendFormat": "Active_file - File-backed memory on active LRU list"
      },
      {
       "expr": "node_memory_Active_anon_bytes{instance=\"$instance\"}",
       "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=\"$instance\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=\"$instance\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=\"$instance\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "Memory Shared and Mapped",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{instance=\"$instance\"}",
       "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=\"$instance\"}",
       "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
      }
     ]
    },
    {
     "title": "Memory Slab",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=\"$instance\"}",
       "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{instance=\"$instance\"}",
       "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
      }
     ]
    },
    {
     "title": "Memory Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{instance=\"$instance\"}",
       "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{instance=\"$instance\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=\"$instance\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "Memory Bounce",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Bounce_bytes{instance=\"$instance\"}",
       "legendFormat": "Bounce - Memory used for block device bounce buffers"
      }
     ]
    },
    {
     "title": "Memory Anonymous",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{instance=\"$instance\"}",
       "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{instance=\"$instance\"}",
       "legendFormat": "AnonPages - Memory in user pages not backed by files"
      }
     ]
    },
    {
     "title": "Memory Kernel",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 103 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{instance=\"$instance\"}",
       "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
      }
     ]
    },
    {
     "title": "Memory HugePages Counter",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{instance=\"$instance\"}",
       "legendFormat": "HugePages_Free - Huge pages in the pool that are not yet allocated"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{instance=\"$instance\"}",
       "legendFormat": "HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
      },
      {
       "expr": "node_memory_HugePages_Surp{instance=\"$instance\"}",
       "legendFormat": "HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
      }
     ]
    },
    {
     "title": "Memory HugePages Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 113 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Total{instance=\"$instance\"}",
       "legendFormat": "HugePages - Total size of the pool of huge pages"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{instance=\"$instance\"}",
       "legendFormat": "Hugepagesize - Huge Page size"
      }
     ]
    },
    {
     "title": "Memory DirectMap",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_DirectMap1G{instance=\"$instance\"}",
       "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap2M_bytes{instance=\"$instance\"}",
       "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap4k_bytes{instance=\"$instance\"}",
       "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
      }
     ]
    },
    {
     "title": "Memory Unevictable and MLocked",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 123 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Unevictable_bytes{instance=\"$instance\"}",
       "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
      },
      {
       "expr": "node_memory_Mlocked_bytes{instance=\"$instance\"}",
       "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
      }
     ]
    },
    {
     "title": "Memory NFS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_NFS_Unstable_bytes{instance=\"$instance\"}",
       "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet commited to the storage"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Detail Vmstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pages In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "short", "label": "Pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{instance=\"$instance\"}[5m])",
       "legendFormat": "Pagesin - Page in operations"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{instance=\"$instance\"}[5m])",
       "legendFormat": "Pagesout - Page out operations"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 134 },
     "yaxes": [
      { "format": "short", "label": "Pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=\"$instance\"}[5m])",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=\"$instance\"}[5m])",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "Memory Page Operations",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgdeactivate{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgdeactivate - Pages moved from active to inactive"
      },
      {
       "expr": "irate(node_vmstat_pgfree{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgfree - Page free operations"
      },
      {
       "expr": "irate(node_vmstat_pgactivate{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgactivate - Pages moved from inactive to active"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 144 },
     "yaxes": [
      { "format": "short", "label": "Faults" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgfault{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgfault - Page major and minor fault operations"
      },
      {
       "expr": "irate(node_vmstat_pgmajfault{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgmajfault - Major page fault operations"
      },
      {
       "expr": "irate(node_vmstat_pgfault{instance=\"$instance\"}[5m]) - irate(node_vmstat_pgmajfault{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgminfault - Minnor page fault operations"
      }
     ]
    },
    {
     "title": "Memory Pages Reclaimed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_kswapd_inodesteal{instance=\"$instance\"}[5m])",
       "legendFormat": "Kswapd_inodesteal - Pages reclaimed via kswapd inode freeing"
      },
      {
       "expr": "irate(node_vmstat_pginodesteal{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgindesteal - Pages reclaimed via inode freeing"
      }
     ]
    },
    {
     "title": "Memory Calls Reclaimed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 154 },
     "yaxes": [
      { "format": "short", "label": "Calls" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pageoutrun{instance=\"$instance\"}[5m])",
       "legendFormat": "Pageoutrun - Kswapd calls to page reclaim"
      },
      {
       "expr": "irate(node_vmstat_allocstall{instance=\"$instance\"}[5m])",
       "legendFormat": "Allocstall - Direct reclaim calls"
      },
      {
       "expr": "irate(node_vmstat_zone_reclaim_failed{instance=\"$instance\"}[5m])",
       "legendFormat": "Zone_reclaim_failed - Zone reclaim failures"
      }
     ]
    },
    {
     "title": "Memory Page Rotate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 164 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgrotated{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgrotated - Pages rotated to tail of the LRU"
      }
     ]
    },
    {
     "title": "Memory Page Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 164 },
     "yaxes": [
      { "format": "short", "label": "Calls" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_drop_pagecache{instance=\"$instance\"}",
       "legendFormat": "Drop_pagecache - Calls to drop page cache pages"
      },
      {
       "expr": "node_vmstat_drop_slab{instance=\"$instance\"}",
       "legendFormat": "Drop_slab - Calls to drop slab cache pages"
      }
     ]
    },
    {
     "title": "Memory Scan Slab",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_slabs_scanned{instance=\"$instance\"}[5m])",
       "legendFormat": "Slabs_scanned - Slab pages scanned"
      }
     ]
    },
    {
     "title": "Memory Unevictable Pages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 174 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_unevictable_pgs_cleared{instance=\"$instance\"}[5m])",
       "legendFormat": "Unevictable_pgs_cleared - Unevictable pages cleared"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_culled{instance=\"$instance\"}[5m])",
       "legendFormat": "Unevictable_pgs_culled - Unevictable pages culled"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_mlocked{instance=\"$instance\"}[5m])",
       "legendFormat": "Unevictable_pgs_mlocked - Unevictable pages mlocked"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_munlocked{instance=\"$instance\"}[5m])",
       "legendFormat": "Unevictable_pgs_munlocked - Unevictable pages munlocked"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_rescued{instance=\"$instance\"}[5m])",
       "legendFormat": "Unevictable_pgs_rescued- Unevictable pages rescued"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_scanned{instance=\"$instance\"}[5m])",
       "legendFormat": "Unevictable_pgs_scanned - Unevictable pages scanned"
      },
      {
       "expr": "irate(node_vmstat_unevictable_pgs_stranded{instance=\"$instance\"}[5m])",
       "legendFormat": "unevictable_pgs_stranded - Unevictable pages stranded"
      }
     ]
    },
    {
     "title": "Memory Page Allocation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 184 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgalloc_dma{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgalloc_dma - Dma mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_dma32{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgalloc_dma32 - Dma32 mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_movable{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgalloc_movable - Movable mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_normal{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgalloc_normal - Normal mem page allocations"
      }
     ]
    },
    {
     "title": "Memory Page Refill",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 184 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgrefill_dma{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgrefill_dma - Dma mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_dma32{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgrefill_dma32 - Dma32 mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_movable{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgrefill_movable - Movable mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_normal{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgrefill_normal - Normal mem pages inspected in refill_inactive_zone"
      }
     ]
    },
    {
     "title": "Memory Page Steal Direct",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 194 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgsteal_direct_dma{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgsteal_direct_dma - Dma mem pages stealed"
      },
      {
       "expr": "irate(node_vmstat_pgsteal_direct_dma32{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgsteal_direct_dma32 - Dma32 mem pages scanned"
      },
      {
       "expr": "irate(node_vmstat_pgsteal_direct_movable{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgsteal_direct_movable - Movable mem pages scanned"
      },
      {
       "expr": "irate(node_vmstat_pgsteal_direct_normal{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgsteal_direct_normal - Normal mem pages scanned"
      }
     ]
    },
    {
     "title": "Memory Page Steal Kswapd",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 194 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgsteal_kswapd_dma{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgsteal_kswapd_dma - Dma mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgsteal_kswapd_dma32{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgsteal_kswapd_dma32 - Dma32 mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgsteal_kswapd_movable{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgsteal_kswapd_movable - Movable mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgsteal_kswapd_normal{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgsteal_kswapd_normal - Normal mem pages scanned by kswapd"
      }
     ]
    },
    {
     "title": "Memory Scan Direct",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 204 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgscan_direct_dma{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgscan_direct_dma - Dma mem pages scanned"
      },
      {
       "expr": "irate(node_vmstat_pgscan_direct_dma32{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgscan_direct_dma32 - Dma32 mem pages scanned"
      },
      {
       "expr": "irate(node_vmstat_pgscan_direct_movable{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgscan_direct_movable - Movable mem pages scanned"
      },
      {
       "expr": "irate(node_vmstat_pgscan_direct_normal{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgscan_direct_normal - Normal mem pages scanned"
      }
     ]
    },
    {
     "title": "Memory Scan Kswapd",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 204 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgscan_kswapd_dma{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgscan_kswapd_dma - Dma mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgscan_kswapd_dma32{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgscan_kswapd_dma32 - Dma32 mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgscan_kswapd_movable{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgscan_kswapd_movable - Movable mem pages scanned by kswapd"
      },
      {
       "expr": "irate(node_vmstat_pgscan_kswapd_normal{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgscan_kswapd_normal - Normal mem pages scanned by kswapd"
      }
     ]
    },
    {
     "title": "Memory Page Compact",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 214 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_free_scanned{instance=\"$instance\"}[5m])",
       "legendFormat": "Compact_free_scanned - Pages scanned for freeing by compaction daemon"
      },
      {
       "expr": "irate(node_vmstat_compact_isolated{instance=\"$instance\"}[5m])",
       "legendFormat": "Compact_isolated - Page isolations for memory compaction"
      },
      {
       "expr": "irate(node_vmstat_compact_migrate_scanned{instance=\"$instance\"}[5m])",
       "legendFormat": "Compact_migrate_scanned - Pages scanned for migration by compaction daemon"
      }
     ]
    },
    {
     "title": "Memory Compactions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 214 },
     "yaxes": [
      { "format": "short", "label": "Compactions" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_compact_fail{instance=\"$instance\"}[5m])",
       "legendFormat": "Compact_fail - Unsuccessful compactions for high order allocations"
      },
      {
       "expr": "irate(node_vmstat_compact_stall{instance=\"$instance\"}[5m])",
       "legendFormat": "Compact_stall - Failures to even start compacting"
      },
      {
       "expr": "irate(node_vmstat_compact_success{instance=\"$instance\"}[5m])",
       "legendFormat": "Compact_sucess - Successful compactions for high order allocations"
      }
     ]
    },
    {
     "title": "Memory Kswapd Watermark",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 224 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_kswapd_high_wmark_hit_quickly{instance=\"$instance\"}",
       "legendFormat": "Kswapd_high_wmark_hit_quickly - Times high watermark reached quickly"
      },
      {
       "expr": "node_vmstat_kswapd_low_wmark_hit_quickly{instance=\"$instance\"}",
       "legendFormat": "Kswapd_low_wmark_hit_quickly - Times low watermark reached quickly"
      }
     ]
    },
    {
     "title": "Memory Buddy Alloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 224 },
     "yaxes": [
      { "format": "short", "label": "Allocations" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_htlb_buddy_alloc_fail{instance=\"$instance\"}",
       "legendFormat": "Htlb_buddy_alloc_fail - Huge TLB page buddy allocation failures"
      },
      {
       "expr": "node_vmstat_htlb_buddy_alloc_success{instance=\"$instance\"}",
       "legendFormat": "Htlb_buddy_alloc_success - Huge TLB page buddy allocation successes"
      }
     ]
    },
    {
     "title": "Memory Numa Allocations",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 234 },
     "yaxes": [
      { "format": "short", "label": "Allocations" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_foreign{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_foreign - Foreign NUMA zone allocations"
      },
      {
       "expr": "irate(node_vmstat_numa_hit{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_hit - Successful allocations from preferred NUMA zone"
      },
      {
       "expr": "irate(node_vmstat_numa_interleave{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_interleave - Interleaved NUMA allocations in each zone for each NUMA node"
      },
      {
       "expr": "irate(node_vmstat_numa_local{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_local - Successful allocations from local NUMA zone"
      },
      {
       "expr": "irate(node_vmstat_numa_miss{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_miss - Unsuccessful allocations from preferred NUMA zona"
      },
      {
       "expr": "irate(node_vmstat_numa_other{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_other - Unsuccessful allocations from local NUMA zone"
      }
     ]
    },
    {
     "title": "Memory Numa Page Migrations",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 234 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_pages_migrated{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_pages_migrated - NUMA page migrations"
      },
      {
       "expr": "irate(node_vmstat_pgmigrate_fail{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgmigrate_fail - Unsuccessful NUMA page migrations"
      },
      {
       "expr": "irate(node_vmstat_pgmigrate_success{instance=\"$instance\"}[5m])",
       "legendFormat": "Pgmigrate_success - Successful NUMA page migrations"
      }
     ]
    },
    {
     "title": "Memory Numa Hints",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 244 },
     "yaxes": [
      { "format": "short", "label": "HInts" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_hint_faults{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_hint_faults - NUMA hint faults trapped"
      },
      {
       "expr": "irate(node_vmstat_numa_hint_faults_local{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_hint_faults_local - Hinting faults to local nodes"
      }
     ]
    },
    {
     "title": "Memory Numa Table Updates",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 244 },
     "yaxes": [
      { "format": "short", "label": "Updates" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_numa_pte_updates{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_pte_updates - NUMA page table entry updates"
      },
      {
       "expr": "irate(node_vmstat_numa_huge_pte_updates{instance=\"$instance\"}[5m])",
       "legendFormat": "Numa_huge_pte_updates - NUMA huge page table entry updates"
      }
     ]
    },
    {
     "title": "Memory THP Splits",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 254 },
     "yaxes": [
      { "format": "short", "label": "Splits" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_thp_split{instance=\"$instance\"}[5m])",
       "legendFormat": "Thp_split - Transparent huge page splits"
      }
     ]
    },
    {
     "title": "Memory Workingset",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 254 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_workingset_activate{instance=\"$instance\"}[5m])",
       "legendFormat": "Workingset_activate - Page activations to form the working set"
      },
      {
       "expr": "irate(node_vmstat_workingset_nodereclaim{instance=\"$instance\"}[5m])",
       "legendFormat": "Workingset_nodereclaim - NUMA node working set page reclaims"
      },
      {
       "expr": "irate(node_vmstat_workingset_refault{instance=\"$instance\"}[5m])",
       "legendFormat": "Workingset_refault - Refaults of previously evicted pages"
      }
     ]
    },
    {
     "title": "Memory THP Allocations",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 264 },
     "yaxes": [
      { "format": "short", "label": "Allocations" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_thp_collapse_alloc{instance=\"$instance\"}[5m])",
       "legendFormat": "Thp_collapse_alloc - Transparent huge page collapse allocations"
      },
      {
       "expr": "irate(node_vmstat_thp_collapse_alloc_failed{instance=\"$instance\"}[5m])",
       "legendFormat": "Thp_collapse_alloc_failed - Transparent huge page collapse allocation failures"
      },
      {
       "expr": "irate(node_vmstat_thp_zero_page_alloc{instance=\"$instance\"}[5m])",
       "legendFormat": "Thp_zero_page_alloc - Transparent huge page zeroed page allocations"
      },
      {
       "expr": "irate(node_vmstat_thp_zero_page_alloc_failed{instance=\"$instance\"}[5m])",
       "legendFormat": "Thp_zero_page_alloc_failed - Transparent huge page zeroed page allocation failures"
      },
      {
       "expr": "irate(node_vmstat_thp_fault_alloc{instance=\"$instance\"}[5m])",
       "legendFormat": "Thp_fault_alloc - Transparent huge page fault allocations"
      },
      {
       "expr": "irate(node_vmstat_thp_fault_fallback{instance=\"$instance\"}[5m])",
       "legendFormat": "Thp_fault_fallback - Transparent huge page fault fallbacks"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Detail Vmstat Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Page Active",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_active_anon{instance=\"$instance\"}",
       "legendFormat": "Active_anon - Active anonymous memory pages"
      },
      {
       "expr": "node_vmstat_nr_active_file{instance=\"$instance\"}",
       "legendFormat": "Active_file - Active file memory memory pages"
      }
     ]
    },
    {
     "title": "Memory Page Inactive",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_inactive_anon{instance=\"$instance\"}",
       "legendFormat": "Inactive_anon - Inactive anonymous memory pages in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_inactive_file{instance=\"$instance\"}",
       "legendFormat": "Inactive_file - Inactive file memory pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Reclaimed / Unreclaimed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 275 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_slab_reclaimable{instance=\"$instance\"}",
       "legendFormat": "Reclaimable - Instantaneous reclaimable slab pages"
      },
      {
       "expr": "node_vmstat_nr_slab_unreclaimable{instance=\"$instance\"}",
       "legendFormat": "Unreclaimable - Instantaneous unreclaimable slab pages"
      }
     ]
    },
    {
     "title": "Memory Page Free / Written",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 275 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_free_pages{instance=\"$instance\"}",
       "legendFormat": "Free_pages - Free pages"
      },
      {
       "expr": "node_vmstat_nr_written{instance=\"$instance\"}",
       "legendFormat": "Written - Pages written out in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Dirty / Bounce",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 285 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_dirty{instance=\"$instance\"}",
       "legendFormat": "Dirty - Pages in dirty state"
      },
      {
       "expr": "node_vmstat_nr_bounce{instance=\"$instance\"}",
       "legendFormat": "Bounce - Bounce buffer pages"
      }
     ]
    },
    {
     "title": "Memory Pages Unevictable / Mlock",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 285 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_unevictable{instance=\"$instance\"}",
       "legendFormat": "Unevictable - Unevictable pages"
      },
      {
       "expr": "node_vmstat_nr_mlock{instance=\"$instance\"}",
       "legendFormat": "Mlock - Pages under mlock"
      }
     ]
    },
    {
     "title": "Memory Page Shmem / Mapped",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 295 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_shmem{instance=\"$instance\"}",
       "legendFormat": "Shmem - Shared memory pages"
      },
      {
       "expr": "node_vmstat_nr_mapped{instance=\"$instance\"}",
       "legendFormat": "Mapped - Mapped pagecache pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Kernel_stack",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 295 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_kernel_stack{instance=\"$instance\"}",
       "legendFormat": "Kernel_stack - Pages of kernel stack"
      }
     ]
    },
    {
     "title": "Memory Pages Writeback",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 305 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_writeback{instance=\"$instance\"}",
       "legendFormat": "Writeback - Writeback pages"
      },
      {
       "expr": "node_vmstat_nr_writeback_temp{instance=\"$instance\"}",
       "legendFormat": "Writeback_temp - Temporary writeback pages"
      }
     ]
    },
    {
     "title": "Memory Page File_pages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 305 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_file_pages{instance=\"$instance\"}",
       "legendFormat": "File_pages - File pagecache pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Dirty Threshold",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 315 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_dirty_background_threshold{instance=\"$instance\"}",
       "legendFormat": "Dirty_background_threshold - Background writeback threshold"
      },
      {
       "expr": "node_vmstat_nr_dirty_threshold{instance=\"$instance\"}",
       "legendFormat": "Dirty_threshold - Dirty throttling threshold"
      }
     ]
    },
    {
     "title": "Memory Page Unstable / Dirtied",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 315 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_unstable{instance=\"$instance\"}",
       "legendFormat": "Unstable - Pages unstable state in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_dirtied{instance=\"$instance\"}",
       "legendFormat": "Dirtied - Pages entering dirty state in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Page_table_pages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 325 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_page_table_pages{instance=\"$instance\"}",
       "legendFormat": "Page_table_pages - Page table pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Alloc_batch",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 325 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_alloc_batch{instance=\"$instance\"}",
       "legendFormat": "Alloc_batch - Pages allocated to other zones due to insufficient memory for each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Isolated",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 335 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_isolated_anon{instance=\"$instance\"}",
       "legendFormat": "Isolated_anon - Isolated anonymous memory pages in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_isolated_file{instance=\"$instance\"}",
       "legendFormat": "Isolated_file - Isolated file memory pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Anon",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 335 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_anon_pages{instance=\"$instance\"}",
       "legendFormat": "Anon_pages - Anonymous mapped pagecache pages in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_anon_transparent_hugepages{instance=\"$instance\"}",
       "legendFormat": "Anon_transparent_hugepages - Anonymous transparent huge pages in each zone for each NUMA node"
      }
     ]
    },
    {
     "title": "Memory Page Misc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 345 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_free_cma{instance=\"$instance\"}",
       "legendFormat": "Free_cma - Free Contiguous Memory Allocator pages in each zone for each NUMA node"
      },
      {
       "expr": "node_vmstat_nr_vmscan_write{instance=\"$instance\"}",
       "legendFormat": "Vmscan_write - Pages written by VM scanner from LRU"
      },
      {
       "expr": "node_vmstat_nr_vmscan_immediate_reclaim{instance=\"$instance\"}",
       "legendFormat": "Immediate_reclaim - Prioritise for reclaim when writeback ends in each zone for each NUMA node"
      }
     ]
    }
   ]
  },
  {
   "title": "System Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 346 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "irate(node_intr_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 346 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=\"$instance\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=\"$instance\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=\"$instance\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Interrupts Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 356 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_interrupts_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{ type }} - {{ info }}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 356 },
     "yaxes": [
      { "format": "short", "label": "Descriptors" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{instance=\"$instance\"}",
       "legendFormat": "Maximum open file descriptors"
      },
      {
       "expr": "process_open_fds{instance=\"$instance\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 366 },
     "yaxes": [
      { "format": "short", "label": "Entropy" }
     ],
     "targets": [
      {
       "expr": "node_entropy_available_bits{instance=\"$instance\"}",
       "legendFormat": "Entropy available to random number generators"
      }
     ]
    },
    {
     "title": "Processes State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 366 },
     "yaxes": [
      { "format": "short", "label": "Processes" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{instance=\"$instance\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{instance=\"$instance\"}",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "Processes Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 376 },
     "yaxes": [
      { "format": "short", "label": "Forks / sec" }
     ],
     "targets": [
      {
       "expr": "rate(node_forks_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "Processes Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 376 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=\"$instance\"}",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
       "legendFormat": "Processes resident memory size in bytes"
      }
     ]
    },
    {
     "title": "Time Syncronized Status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 386 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_timex_sync_status{instance=\"$instance\"}",
       "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no)"
      },
      {
       "expr": "node_timex_frequency_adjustment_ratio{instance=\"$instance\"}",
       "legendFormat": "Local clock frequency adjustment"
      }
     ]
    },
    {
     "title": "Time Syncronized Drift",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 386 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{instance=\"$instance\"}",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "node_timex_offset_seconds{instance=\"$instance\"}",
       "legendFormat": "Time offset in between local system and reference clock"
      },
      {
       "expr": "node_timex_maxerror_seconds{instance=\"$instance\"}",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    },
    {
     "title": "Hardware temperature monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 396 },
     "yaxes": [
      { "format": "celsius", "label": "Temperature" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{instance=\"$instance\"}",
       "legendFormat": "{{ chip }} {{ sensor }} temp"
      },
      {
       "expr": "node_hwmon_temp_crit_celsius{instance=\"$instance\"}",
       "legendFormat": "{{ chip }} {{ sensor }} Critical"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps Completed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 397 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 397 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "Disk R/W Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 407 },
     "yaxes": [
      { "format": "ms", "label": "Millisec. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Read time ms"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Write time ms"
      }
     ]
    },
    {
     "title": "Disk IOs Weighted",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 407 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - IO time weighted"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 417 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_merged_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Read merged"
      },
      {
       "expr": "irate(node_disk_writes_merged_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Write merged"
      }
     ]
    },
    {
     "title": "Milliseconds Spent Doing I/Os",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 417 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - IO time ms"
      }
     ]
    },
    {
     "title": "Disk IOs Current in Progress",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 427 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_now{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - IO now"
      }
     ]
    },
    {
     "title": "Open Error File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 427 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "node_textfile_scrape_error{instance=\"$instance\"}",
       "legendFormat": "Textfile scrape error (1 = true)"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 428 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 428 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 438 },
     "yaxes": [
      { "format": "short", "label": "Files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=\"$instance\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{instance=\"$instance\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 438 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - File nodes total"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 448 },
     "yaxes": [
      { "format": "short", "label": "Read Only" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=\"$instance\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - ReadOnly"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 449 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 449 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 459 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Compressed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 459 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_compressed_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive compressed"
      },
      {
       "expr": "irate(node_network_transmit_compressed_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit compressed"
      }
     ]
    },
    {
     "title": "Network Traffic Multicast",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 469 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_multicast_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive multicast"
      }
     ]
    },
    {
     "title": "Network Traffic Fifo",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 469 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_fifo_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive fifo"
      },
      {
       "expr": "irate(node_network_transmit_fifo_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit fifo"
      }
     ]
    },
    {
     "title": "Network Traffic Frame",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 479 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_frame_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Receive frame"
      }
     ]
    },
    {
     "title": "Network Traffic Carrier",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 479 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_carrier_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Statistic transmit_carrier"
      }
     ]
    },
    {
     "title": "Network Traffic Colls",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 489 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_colls_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{device}} - Transmit colls"
      }
     ]
    },
    {
     "title": "NF Contrack",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 489 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=\"$instance\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=\"$instance\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 499 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_arp_entries{instance=\"$instance\"}",
       "legendFormat": "{{ device }} - ARP entries"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockstat TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 500 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=\"$instance\"}",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=\"$instance\"}",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_mem{instance=\"$instance\"}",
       "legendFormat": "TCP_mem - Used memory for tcp"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=\"$instance\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=\"$instance\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 500 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{instance=\"$instance\"}",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=\"$instance\"}",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_mem{instance=\"$instance\"}",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 510 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{instance=\"$instance\"}",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 510 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{instance=\"$instance\"}",
       "legendFormat": "TCP_mem_bytes - "
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{instance=\"$instance\"}",
       "legendFormat": "UDP_mem_bytes - "
      }
     ]
    },
    {
     "title": "Sockstat FRAG / RAW",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 520 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{instance=\"$instance\"}",
       "legendFormat": "FRAG_inuse - Frag sockets currently in use"
      },
      {
       "expr": "node_sockstat_FRAG_memory{instance=\"$instance\"}",
       "legendFormat": "FRAG_memory - Used memory for frag"
      },
      {
       "expr": "node_sockstat_RAW_inuse{instance=\"$instance\"}",
       "legendFormat": "RAW_inuse - Raw sockets currently in use"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat IP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 521 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_InReceives{instance=\"$instance\"}[5m])",
       "legendFormat": "InReceives - IP inreceives"
      },
      {
       "expr": "irate(node_netstat_Ip_InDelivers{instance=\"$instance\"}[5m])",
       "legendFormat": "InDelivers - IP indelivers"
      },
      {
       "expr": "irate(node_netstat_Ip_OutRequests{instance=\"$instance\"}[5m])",
       "legendFormat": "OutRequests - IP outrequests"
      }
     ]
    },
    {
     "title": "Netstat IP In / Out Octets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 521 },
     "yaxes": [
      { "format": "short", "label": "Octects out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InOctets{instance=\"$instance\"}[5m])",
       "legendFormat": "InOctets - Received octets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"$instance\"}[5m])",
       "legendFormat": "OutOctets - Sent octets"
      }
     ]
    },
    {
     "title": "Netstat IP Bcast",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 531 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InBcastPkts{instance=\"$instance\"}[5m])",
       "legendFormat": "InBcastPkts - Received IP broadcast datagrams"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutBcastPkts{instance=\"$instance\"}[5m])",
       "legendFormat": "OutBcastPkts - Sent IP broadcast datagrams"
      }
     ]
    },
    {
     "title": "Netstat IP Bcast Octets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 531 },
     "yaxes": [
      { "format": "short", "label": "Octets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InBcastOctets{instance=\"$instance\"}[5m])",
       "legendFormat": "InBcastOctets - Received IP broadcast octets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutBcastOctets{instance=\"$instance\"}[5m])",
       "legendFormat": "OutBcastOctets - Sent IP broadcast octects"
      }
     ]
    },
    {
     "title": "Netstat IP Mcast",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 541 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InMcastPkts{instance=\"$instance\"}[5m])",
       "legendFormat": "InMcastPkts - Received IP multicast datagrams"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutMcastPkts{instance=\"$instance\"}[5m])",
       "legendFormat": "OutMcastPkts - Sent IP multicast datagrams"
      }
     ]
    },
    {
     "title": "Netstat IP Mcast Octets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 541 },
     "yaxes": [
      { "format": "short", "label": "Octets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InMcastOctets{instance=\"$instance\"}[5m])",
       "legendFormat": "InMcastOctets - Received IP multicast octets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutMcastOctets{instance=\"$instance\"}[5m])",
       "legendFormat": "OutMcastOctets - Sent IP multicast octets"
      }
     ]
    },
    {
     "title": "Netstat IP Forwarding",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 551 },
     "yaxes": [
      { "format": "short", "label": "Datagrams" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_ForwDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "ForwDatagrams - IP outforwdatagrams"
      },
      {
       "expr": "irate(node_netstat_Ip_Forwarding{instance=\"$instance\"}[5m])",
       "legendFormat": "Forwarding - IP forwarding"
      }
     ]
    },
    {
     "title": "Netstat IP Fragmented",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 551 },
     "yaxes": [
      { "format": "short", "label": "Datagrams" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_FragCreates{instance=\"$instance\"}[5m])",
       "legendFormat": "FragCreates - IP fragmentation creations"
      },
      {
       "expr": "irate(node_netstat_Ip_FragFails{instance=\"$instance\"}[5m])",
       "legendFormat": "FragFails - IP fragmentation failures"
      },
      {
       "expr": "irate(node_netstat_Ip_FragOKs{instance=\"$instance\"}[5m])",
       "legendFormat": "FragOKs - IP fragmentation oks"
      }
     ]
    },
    {
     "title": "Netstat IP ECT / CEP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 561 },
     "yaxes": [
      { "format": "short", "label": "Datagrams" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InCEPkts{instance=\"$instance\"}[5m])",
       "legendFormat": "InCEPkts - Congestion Experimented datagrams in"
      },
      {
       "expr": "irate(node_netstat_IpExt_InECT0Pkts{instance=\"$instance\"}[5m])",
       "legendFormat": "InECT0Pkts - Datagrams received with ECT(0)"
      },
      {
       "expr": "irate(node_netstat_IpExt_InECT1Pkts{instance=\"$instance\"}[5m])",
       "legendFormat": "InECT1Pkt - Datarams received with ECT(1)"
      },
      {
       "expr": "irate(node_netstat_IpExt_InNoECTPkts{instance=\"$instance\"}[5m])",
       "legendFormat": "InNoECTPkts - Datagrams received with NOECT"
      }
     ]
    },
    {
     "title": "Netstat IP Reasambled",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 561 },
     "yaxes": [
      { "format": "short", "label": "Datagrams" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_ReasmFails{instance=\"$instance\"}[5m])",
       "legendFormat": "ReasmFails - IP reassembly failures"
      },
      {
       "expr": "irate(node_netstat_Ip_ReasmOKs{instance=\"$instance\"}[5m])",
       "legendFormat": "ReasmOKs - IP reassembly oks"
      },
      {
       "expr": "irate(node_netstat_Ip_ReasmReqds{instance=\"$instance\"}[5m])",
       "legendFormat": "ReasmReqds - IP reassembly requireds"
      },
      {
       "expr": "irate(node_netstat_Ip_ReasmTimeout{instance=\"$instance\"}[5m])",
       "legendFormat": "ReasmTimeout - IP reasmtimeout"
      }
     ]
    },
    {
     "title": "Netstat IP Errors / Discards",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 571 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_InDiscards{instance=\"$instance\"}[5m])",
       "legendFormat": "InDiscards - IP indiscards"
      },
      {
       "expr": "irate(node_netstat_Ip_InHdrErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InHdrErrors - IP inhdrerrors"
      },
      {
       "expr": "irate(node_netstat_Ip_InUnknownProtos{instance=\"$instance\"}[5m])",
       "legendFormat": "InUnknownProtos - IP inunknownprotos"
      },
      {
       "expr": "irate(node_netstat_Ip_OutDiscards{instance=\"$instance\"}[5m])",
       "legendFormat": "OutDiscards - IP outdiscards"
      },
      {
       "expr": "irate(node_netstat_Ip_OutNoRoutes{instance=\"$instance\"}[5m])",
       "legendFormat": "OutNoRoutes - IP outnoroutes"
      },
      {
       "expr": "irate(node_netstat_IpExt_InNoRoutes{instance=\"$instance\"}[5m])",
       "legendFormat": "InNoRoutes - IP datagrams discarded due to no routes in forwarding path"
      },
      {
       "expr": "irate(node_netstat_IpExt_InCsumErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InCsumErrors - IP datagrams with checksum errors"
      },
      {
       "expr": "irate(node_netstat_IpExt_InTruncatedPkts{instance=\"$instance\"}[5m])",
       "legendFormat": "InTruncatedPkts - IP datagrams discarded due to frame not carrying enough data"
      },
      {
       "expr": "irate(node_netstat_Ip_InAddrErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InAddrErrors - IP inaddrerrors"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Segments",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 572 },
     "yaxes": [
      { "format": "short", "label": "Segments out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InCsumErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InCsumErrors - Segments received with checksum errors"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=\"$instance\"}[5m])",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      },
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=\"$instance\"}[5m])",
       "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutRsts{instance=\"$instance\"}[5m])",
       "legendFormat": "OutRsts - Segments sent containing the RST flag"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=\"$instance\"}[5m])",
       "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$instance\"}[5m])",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 572 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"$instance\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{instance=\"$instance\"}",
       "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
      }
     ]
    },
    {
     "title": "TCP Retransmission",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 582 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_RtoMax{instance=\"$instance\"}",
       "legendFormat": "RtoMax - Maximum value permitted by a TCP implementation for the retransmission timeout, measured in milliseconds"
      },
      {
       "expr": "node_netstat_Tcp_RtoMin{instance=\"$instance\"}",
       "legendFormat": "RtoMin - Minimum value permitted by a TCP implementation for the retransmission timeout, measured in milliseconds"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 582 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"$instance\"}[5m])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "irate(node_netstat_Tcp_AttemptFails{instance=\"$instance\"}[5m])",
       "legendFormat": "AttemptFails - TCP connections that have made a direct transition to the CLOSED state from either the SYN-SENT and SYN-RCVD"
      },
      {
       "expr": "irate(node_netstat_Tcp_EstabResets{instance=\"$instance\"}[5m])",
       "legendFormat": "EstabResets - TCP connections that have made a direct transition to the CLOSED state from either the ESTABLISHED state or the CLOSE-WAIT state"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"$instance\"}[5m])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat TCP Linux MIPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Aborts / Tiemouts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 583 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnClose{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPAbortOnClose - Connections aborted due to early user close"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnData{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPAbortOnData - Connections aborted due to unexpected data"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnLinger{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPAbortOnLinger - Connections aborted in lingered state after being closed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnMemory{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPAbortOnMemory - Connections aborted before attached to a socket"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnTimeout{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPAbortOnTimeout - Connections aborted due timeout"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortFailed{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPAbortFailed - Connections aborted without send RST due insuffient memory"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPTimeouts{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPTimeouts - Other TCP connections timeouts"
      }
     ]
    },
    {
     "title": "TCP Delayed ACK",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 583 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_DelayedACKLocked{instance=\"$instance\"}[5m])",
       "legendFormat": "DelayedACKLocked - Delayed acks further delayed because of locked socket"
      },
      {
       "expr": "irate(node_netstat_TcpExt_DelayedACKLost{instance=\"$instance\"}[5m])",
       "legendFormat": "DelayedACKLost - Times quick ack mode was activated"
      },
      {
       "expr": "irate(node_netstat_TcpExt_DelayedACKs{instance=\"$instance\"}[5m])",
       "legendFormat": "DelayedACKs - Delayed acks sent"
      }
     ]
    },
    {
     "title": "TCP SynCookie / Challenge",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 593 },
     "yaxes": [
      { "format": "short", "label": "Counter out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=\"$instance\"}[5m])",
       "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=\"$instance\"}[5m])",
       "legendFormat": "SyncookiesRecv - SYN cookies received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=\"$instance\"}[5m])",
       "legendFormat": "SyncookiesSent - SYN cookies sent"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSYNChallenge{instance=\"$instance\"}[5m])",
       "legendFormat": "SynChallenge - Challenge ACKs sent in response to SYN packets"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPChallengeACK{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPChallengeACK - Challenge ACKs sent (RFC 5961 3.2)"
      }
     ]
    },
    {
     "title": "TCP LOSS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 593 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPLossFailures{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPLossFailures - Timeouts in loss state"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPLossProbeRecovery{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPLossProbeRecovery - TCP loss probe recoveries"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPLossProbes{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPLossProbes - Sent TCP loss probes"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPLossUndo{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPLossUndo - Congestion windows recovered without slow start after partial ack"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPLostRetransmit{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPLostRetransmit - Retransmits lost"
      }
     ]
    },
    {
     "title": "TCP DROPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 603 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$instance\"}[5m])",
       "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
      },
      {
       "expr": "irate(node_netstat_TcpExt_LockDroppedIcmps{instance=\"$instance\"}[5m])",
       "legendFormat": "LockDroppedIcmps - ICMP packets dropped because socket was locked"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPDeferAcceptDrop{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDeferAcceptDrop - Dropped ACK frames received by a socket in SYN_RECV state"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPBacklogDrop{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPBacklogDrop - Packets dropped bacause the socket's receive queue was full"
      },
      {
       "expr": "irate(node_netstat_TcpExt_OutOfWindowIcmps{instance=\"$instance\"}[5m])",
       "legendFormat": "OutOfWindowIcmps - ICMP packets dropped because they were out-of-window"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPMinTTLDrop{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPMinTTLDrop - TCP packets dropped under minTTL condition"
      }
     ]
    },
    {
     "title": "TCP Retrans",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 603 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPForwardRetrans{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPForwardRetrans - Packets losts retransmitted with Forward RTO-Recovery"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSlowStartRetrans{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSlowStartRetrans - Packets losts retransmitted after a slow start"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSpuriousRTOs{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSpuriousRTOs - FRTO's successfully detected spurious RTOs"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSpuriousRtxHostQueues{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSpuriousRtxHostQueues - Times detected that the fast clone is not yet freed in tcp_transmit_skb()"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPFullUndo{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFullUndo - Retransmits that undid the CWND reduction"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPRetransFail{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPRetransFail - Failed tcp_retransmit_skb() calls"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPPartialUndo{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPPartialUndo - Congestion windows partially recovered using Hoe heuristic"
      }
     ]
    },
    {
     "title": "TCP Pruned",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 613 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_PruneCalled{instance=\"$instance\"}[5m])",
       "legendFormat": "PruneCalled - Pkts pruned from recv queue because of soc buf overrun"
      },
      {
       "expr": "irate(node_netstat_TcpExt_RcvPruned{instance=\"$instance\"}[5m])",
       "legendFormat": "RcvPruned - Packets pruned from receive queue"
      },
      {
       "expr": "irate(node_netstat_TcpExt_OfoPruned{instance=\"$instance\"}[5m])",
       "legendFormat": "OfoPruned - Packets dropped from out-of-order queue because of socket buffer overrun"
      }
     ]
    },
    {
     "title": "TCP Direct Copy",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 613 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPDirectCopyFromBacklog{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDirectCopyFromBacklog - Packets directly received from backlog"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPDirectCopyFromPrequeue{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDirectCopyFromPrequeue - Packets directly received from prequeue"
      }
     ]
    },
    {
     "title": "TCP TimeWait",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 623 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TW{instance=\"$instance\"}[5m])",
       "legendFormat": "TW - TCP sockets finished time wait in fast timer"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TWKilled{instance=\"$instance\"}[5m])",
       "legendFormat": "TWKilled - TCP sockets finished time wait in slow timer"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TWRecycled{instance=\"$instance\"}[5m])",
       "legendFormat": "TWRecycled - Time wait sockets recycled by time stamp"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPTimeWaitOverflow{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPTimeWaitOverflow - Occurences of time wait bucket overflow"
      }
     ]
    },
    {
     "title": "TCP PAWS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 623 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_PAWSActive{instance=\"$instance\"}[5m])",
       "legendFormat": "PAWSActive - Active connections rejected because of time stamp"
      },
      {
       "expr": "irate(node_netstat_TcpExt_PAWSEstab{instance=\"$instance\"}[5m])",
       "legendFormat": "PAWSEstab - Pkts rejects in estab connections because of timestamp"
      },
      {
       "expr": "irate(node_netstat_TcpExt_PAWSPassive{instance=\"$instance\"}[5m])",
       "legendFormat": "PAWSPassive - Passive connections rejected because of time stamp"
      }
     ]
    },
    {
     "title": "TCP SACK",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 633 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPSackRecovery{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSackRecovery - Times recovered from packet loss by selective acknowledgements"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSackRecoveryFail{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSackRecoveryFail - Issue while recovering packets lost using selective ACK"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSackShiftFallback{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSackShiftFallback - SACKs fallbacks"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSackShifted{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSackShifted - SACKs shifted"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSACKDiscard{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSackDiscard - Discarded due invalid SACK block."
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSackFailures{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSackFailures - Timeouts after SACK recovery"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSackMerged{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSackMerged - SACKs merged"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSACKReneging{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSACKReneging - Bad SACK blocks received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSACKReorder{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSACKReorder - Times detected reordering using SACK"
      }
     ]
    },
    {
     "title": "TCP DSACK",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 633 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPDSACKIgnoredOld{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDSACKIgnoredOld - Discarded packets with duplicate SACK while retransmitting"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPDSACKOfoRecv{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDSACKOfoRecv - DSACKs for out of order packets received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPDSACKOfoSent{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDSACKOfoSent - DSACKs sent for out of order packets"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPDSACKOldSent{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDSACKOldSent - DSACKs sent for old packets"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPDSACKRecv{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDSACKRecv - DSACKs received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPDSACKUndo{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDSACKUndo - Discarded packets with erroneous retransmit"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPDSACKIgnoredNoUndo{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPDSACKIgnoredNoUndo - Discarded packets with duplicate SACK"
      }
     ]
    },
    {
     "title": "TCP FastOpen / FastRetrans",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 643 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPFastOpenActive{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFastOpenActive - Successful outbound TFO connections"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPFastOpenActiveFail{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFastOpenActiveFail - SYN-ACK packets received that did not acknowledge data sent in the SYN packet and caused a retransmissions without SYN data"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPFastOpenCookieReqd{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFastOpenCookieReqd - Inbound SYN packets requesting TFO with TFO set but no cookie"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPFastOpenListenOverflow{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFastOpenListenOverflow - Times the fastopen listen queue overflowed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPFastOpenPassive{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFastOpenPassive - Successful inbound TFO connections"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPFastOpenPassiveFail{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFastOpenPassiveFail - Inbound SYN packets with TFO cookie that was invalid"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPFastRetrans{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFastRetrans - Packets lost fast-retransmitted"
      }
     ]
    },
    {
     "title": "TCP HP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 643 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPHPAcks{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPHPAcks - Acknowledgments not containing data received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPHPHits{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPHPHits - Packets header predicted"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPHPHitsToUser{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPHPHitsToUser - Packets header predicted and directly queued to user"
      }
     ]
    },
    {
     "title": "TCP ZeroWindow",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 653 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPToZeroWindowAdv{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPToZeroWindowAdv - Times window went from zero to non-zero"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPWantZeroWindowAdv{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPWantZeroWindowAdv - Times zero window announced"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPFromZeroWindowAdv{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFromZeroWindowAdv - Times window went from zero to non-zero"
      }
     ]
    },
    {
     "title": "TCP Reorder",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 653 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPFACKReorder{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPFACKReorder - Detected packets with re-ordering using FACK"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPTSReorder{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPTSReorder - Times detected packets with re-ordering using timestamp option"
      }
     ]
    },
    {
     "title": "TCP Reno",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 663 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPRenoFailures{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPRenoFailures - Timeouts after reno fast retransmit"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPRenoRecovery{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPRenoRecovery - Times recovered from packet loss due to fast retransmit"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPRenoRecoveryFail{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPRenoRecoveryFail - Times reno fast retransmits failed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPRenoReorder{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPRenoReorder - Times detected reordering using reno fast retransmit"
      }
     ]
    },
    {
     "title": "TCP ReqQ",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 663 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPReqQFullDoCookies{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPReqQFullDoCookies - Times SYNCOOKIE was replied to client"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPReqQFullDrop{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPReqQFullDrop - Times SYN request was dropped due to disabled syncookies"
      }
     ]
    },
    {
     "title": "TCP Out of order",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 673 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPOFODrop{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPOFODrop - Packets meant to be queued in OFO but dropped because socket rcvbuf limit reached"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPOFOMerge{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPOFOMerge - Packets in OFO that were merged with other packets"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPOFOQueue{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPOFOQueue - Packets queued in OFO queue"
      }
     ]
    },
    {
     "title": "TCP MD5",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 673 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPMD5NotFound{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPMD5NotFound - Times MD5 hash expected but not found"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPMD5Unexpected{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPMD5Unexpected - Times MD5 hash unexpected but found"
      }
     ]
    },
    {
     "title": "TCP Prequeued",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 683 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPPrequeued{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPPrequeued - Packets directly queued to recvmsg prequeue"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPPrequeueDropped{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPPrequeueDropped - Packets dropped from prequeue"
      }
     ]
    },
    {
     "title": "TCP Rcv",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 683 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPRcvCoalesce{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPRcvCoalesce - Times tried to coalesce the receive queue"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPRcvCollapsed{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPRcvCollapsed - Packets collapsed in receive queue due to low socket buffer"
      }
     ]
    },
    {
     "title": "TCP Original Data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 693 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPOrigDataSent{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPOrigDataSent - Outgoing packets with original data"
      }
     ]
    },
    {
     "title": "TCP Filters",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 693 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ArpFilter{instance=\"$instance\"}[5m])",
       "legendFormat": "ArpFilter - Arp packets filtered"
      },
      {
       "expr": "irate(node_netstat_TcpExt_IPReversePathFilter{instance=\"$instance\"}[5m])",
       "legendFormat": "IPReversePathFilter - Packets arrive from non directly connected network"
      }
     ]
    },
    {
     "title": "TCP Pure ACK",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 703 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPPureAcks{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPPureAcks - Acknowledgments not containing data payload received"
      }
     ]
    },
    {
     "title": "TCP Auto Corking",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 703 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPAutoCorking{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPAutoCorking - Times stack detected skb was underused and its flush was deferred"
      }
     ]
    },
    {
     "title": "TCP Issues",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 713 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_BusyPollRxPackets{instance=\"$instance\"}[5m])",
       "legendFormat": "BusyPollRxPackets - Low latency application-fetched packets"
      },
      {
       "expr": "irate(node_netstat_TcpExt_EmbryonicRsts{instance=\"$instance\"}[5m])",
       "legendFormat": "EmbryonicRsts - Resets received for embryonic SYN_RECV sockets"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=\"$instance\"}[5m])",
       "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSchedulerFailed{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPSchedulerFailed - Times receiver scheduled too late for direct processing"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPMemoryPressures{instance=\"$instance\"}[5m])",
       "legendFormat": "TCPMemoryPressures - TCP ran low on memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 714 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "InDatagrams - Datagrams received"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "OutDatagrams - Datagrams sent"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 714 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InCsumErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InCsumErrors - Datagrams with checksum errors"
      },
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
      },
      {
       "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "RcvbufErrors - Datagrams for which not enough socket buffer memory to receive"
      },
      {
       "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "SndbufErrors - Datagrams for which not enough socket buffer memory to transmit"
      },
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=\"$instance\"}[5m])",
       "legendFormat": "NoPorts - Datagrams received on a port with no listener"
      }
     ]
    },
    {
     "title": "UDP Lite In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 724 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_UdpLite_InDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "InDatagrams - Packets received"
      },
      {
       "expr": "irate(node_netstat_UdpLite_OutDatagrams{instance=\"$instance\"}[5m])",
       "legendFormat": "OutDatagrams - Packets sent"
      }
     ]
    },
    {
     "title": "UDP Lite Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 724 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_UdpLite_InCsumErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InCsumErrors - Datagrams with checksum errors"
      },
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
      },
      {
       "expr": "irate(node_netstat_UdpLite_RcvbufErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "RcvbufErrors - Datagrams for which not enough socket buffer memory to receive"
      },
      {
       "expr": "irate(node_netstat_UdpLite_SndbufErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "SndbufErrors - Datagrams for which not enough socket buffer memory to transmit"
      },
      {
       "expr": "irate(node_netstat_UdpLite_NoPorts{instance=\"$instance\"}[5m])",
       "legendFormat": "NoPorts - Datagrams received on a port with no listener"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICMP Errors 1",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 725 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "OutErrors - Messages which this entity did not send due to problems discovered within ICMP, such as a lack of buffers"
      },
      {
       "expr": "irate(node_netstat_Icmp_InDestUnreachs{instance=\"$instance\"}[5m])",
       "legendFormat": "InDestUnreachs - Destination Unreachable messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutDestUnreachs{instance=\"$instance\"}[5m])",
       "legendFormat": "OutDestUnreachs - Destination Unreachable messages sent"
      },
      {
       "expr": "irate(node_netstat_IcmpMsg_InType3{instance=\"$instance\"}[5m])",
       "legendFormat": "InType3 - Destination unreachable"
      },
      {
       "expr": "irate(node_netstat_IcmpMsg_OutType3{instance=\"$instance\"}[5m])",
       "legendFormat": "OutType3 - Destination unreachable"
      },
      {
       "expr": "irate(node_netstat_IcmpMsg_InType11{instance=\"$instance\"}[5m])",
       "legendFormat": "InType11 - Time Exceeded"
      }
     ]
    },
    {
     "title": "ICMP Errors 2",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 725 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InCsumErrors{instance=\"$instance\"}[5m])",
       "legendFormat": "InCsumErrors - Messages with ICMP checksum errors"
      },
      {
       "expr": "irate(node_netstat_Icmp_InTimeExcds{instance=\"$instance\"}[5m])",
       "legendFormat": "InTimeExcds - Time Exceeded messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutTimeExcds{instance=\"$instance\"}[5m])",
       "legendFormat": "OutTimeExcds - Time Exceeded messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_InParmProbs{instance=\"$instance\"}[5m])",
       "legendFormat": "InParmProbs - Parameter Problem messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutParmProbs{instance=\"$instance\"}[5m])",
       "legendFormat": "OutParmProb - Parameter Problem messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_InSrcQuenchs{instance=\"$instance\"}[5m])",
       "legendFormat": "InSrcQuenchs - Source Quench messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutSrcQuenchs{instance=\"$instance\"}[5m])",
       "legendFormat": "OutSrcQuenchs - Source Quench messages sent"
      }
     ]
    },
    {
     "title": "ICMP In / Out - Messages / Redirects",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 735 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InMsgs{instance=\"$instance\"}[5m])",
       "legendFormat": "InMsgs - Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_InRedirects{instance=\"$instance\"}[5m])",
       "legendFormat": "InRedirects - Redirect messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutMsgs{instance=\"$instance\"}[5m])",
       "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutRedirects{instance=\"$instance\"}[5m])",
       "legendFormat": "OutRedirects - Redirect messages sent. For a host, this object will always be zero, since hosts do not send redirects"
      }
     ]
    },
    {
     "title": "ICMP Timestamps",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 735 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InTimestampReps{instance=\"$instance\"}[5m])",
       "legendFormat": "InTimestampReps - Timestamp Reply messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_InTimestamps{instance=\"$instance\"}[5m])",
       "legendFormat": "InTimestamps - Timestamp (request) messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutTimestampReps{instance=\"$instance\"}[5m])",
       "legendFormat": "OutTimestampReps - Timestamp Reply messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutTimestamps{instance=\"$instance\"}[5m])",
       "legendFormat": "OutTimestamps - Timestamp (request) messages sent"
      }
     ]
    },
    {
     "title": "ICMP Echos",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 745 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InEchoReps{instance=\"$instance\"}[5m])",
       "legendFormat": "InEchoReps - Echo Reply messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_InEchos{instance=\"$instance\"}[5m])",
       "legendFormat": "InEchos - Echo (request) messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutEchoReps{instance=\"$instance\"}[5m])",
       "legendFormat": "OutEchoReps - Echo Reply messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutEchos{instance=\"$instance\"}[5m])",
       "legendFormat": "OutEchos - Echo (request) messages sent"
      }
     ]
    },
    {
     "title": "ICMP Masks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 745 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InAddrMaskReps{instance=\"$instance\"}[5m])",
       "legendFormat": "InAddrMaskReps - Address Mask Reply messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_InAddrMasks{instance=\"$instance\"}[5m])",
       "legendFormat": "InAddrMasks - Address Mask Request messages received"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutAddrMaskReps{instance=\"$instance\"}[5m])",
       "legendFormat": "OutAddrMaskReps - Address Mask Reply messages sent"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutAddrMasks{instance=\"$instance\"}[5m])",
       "legendFormat": "OutAddrMasks - Address Mask Request messages sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 746 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape Success",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 746 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=\"$instance\"}",
       "legendFormat": "{{collector}} - Scrape success"
      }
     ]
    }
   ]
  }
 ]
}