apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-harbor-jobservice-hpa
  namespace: {{ .Release.Namespace }}
spec:
  maxReplicas: 8
  metrics:
  - resource:
      name: cpu
      target:
        averageValue: 400m
        type: AverageValue
    type: Resource
  - resource:
      name: memory
      target:
        averageValue: 800Mi
        type: AverageValue
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-jobservice-registry