apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  labels:
    cubepaas.com/creator: linkcloud
  name: interface-name
  namespace: {{ .Release.Namespace }}
{{- if .Values.defaultSettings.hostNetwork }}
value: {{ .Values.defaultSettings.interfaceName }}
{{- else }}
value: 
{{- end }}