apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storagebs-bind
  labels: {{- include "longhorn.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storagebs-role
subjects:
- kind: ServiceAccount
  name: storagebs-service-account
  namespace: {{ include "release_namespace" . }}
