apiVersion: v1
kind: ConfigMap
metadata:
  name: storagebs-storageclass
  namespace: {{ include "release_namespace" . }}
  labels: {{- include "longhorn.labels" . | nindent 4 }}
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: storagebs
      annotations:
        storageclass.kubernetes.io/is-default-class: {{ .Values.persistence.defaultClass | quote }}
      labels: {{- include "longhorn.labels" . | nindent 4 }}
    provisioner: driver.cubepaas.com
    allowVolumeExpansion: true
    reclaimPolicy: "{{ .Values.persistence.reclaimPolicy }}"
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "{{ .Values.persistence.defaultClassReplicaCount }}"
      staleReplicaTimeout: "30"
      fromBackup: ""
      baseImage: ""
      {{- if .Values.persistence.recurringJobs.enable }}
      recurringJobs: '{{ .Values.persistence.recurringJobs.jobList }}'
      {{- end }}
